//
//  AutogenFile.swift
//  AutogenPlugin
//
//  Created by Geoff on 3/15/16.
//  Copyright © 2016 Geoff. All rights reserved.
//

import Foundation

struct Gen
{
    static let Segues          = "Segues"
    static let StoryboardIds   = "StoryboardIds"
    static let Images          = "Images"
}

class FileWriter
{
    private var genFileFullPath    : String = ""
    private var imgMgr             : ImgMgr!
    private var storyboardData     : StoryboardParser!
    private var outfile            : NSFileHandle!
    private var fileOpen           : Bool = false

    static  var TAB = "    "

    init(imgMgr          : ImgMgr,
         storyboardData  : StoryboardParser,
         genFilePath     : String)
    {
        self.imgMgr          = imgMgr
        self.storyboardData  = storyboardData
        self.genFileFullPath = genFilePath

        self.outfile         = NSFileHandle(forWritingAtPath : self.genFileFullPath)

        if (self.outfile == nil)
        {
            print("Error: Failed to open output file ", self.genFileFullPath)
            fileOpen = false
        }
        else
        {
            fileOpen = true
        }
    }

    func writeAutogenData()
    {
        self.writeHeader()

        self.writeStoryboardData()

        self.writeImageData()

        self.outfile.closeFile()

        self.fileOpen = false
    }

    // Func to write all the image names to a file.
    private func writeImageData()
    {
        assert(self.fileOpen)

        if self.imgMgr.images.count > 0
        {
            self.writeArrayToStruct(Gen.Images, array : self.imgMgr.images)
        }
        else
        {
            self.writeCommentLine("No images found.\n")
        }
    }

    // Func to write all the storyboard data to a file.
    private func writeStoryboardData()
    {
        assert(self.fileOpen)

        if self.storyboardData.namedSegues.count > 0
        {
            self.writeArrayToStruct(Gen.Segues, array : self.storyboardData.namedSegues)
        }
        else
        {
            self.writeCommentLine("No named segues found.\n")
        }

        if self.storyboardData.storyboardIDs.count > 0
        {
            self.writeArrayToStruct(Gen.Segues, array: self.storyboardData.storyboardIDs)
        }
        else
        {
            self.writeCommentLine("No storyboard IDs found.\n")
        }
    }


    private func writeHeader()
    {
        self.writeCommentLine("This file is autogenerated.\n\n")
        self.writeCommentLine("Do not edit, it will be overwritten.\n\n")
    }

    // writeArrayToStruct (0).
    // Funct to write an array of image assets to file as an array.
    func writeArrayToStruct(structName : String, array : [ImgAsset])
    {
        assert(array.count > 0)

        self.writeTabLine("struct \(structName)\n\(FileWriter.TAB){\n")

        for item in array
        {
            self.writeTabLine("static let \(item.baseName) = \"\(item.baseName)\"\n")
        }

        self.writeTabLine("\(FileWriter.TAB)}\n\n")
    }

    // writeArrayToStruct (1)
    // Funct to write an array of strings to file as an array.
    func writeArrayToStruct(structName : String, array : [String])
    {
        assert(array.count > 0)

        self.writeTabLine("struct \(structName)\n\(FileWriter.TAB){\n")

        for item in array
        {
            self.writeTabLine("static let \(item) = \"\(item)\"\n")
        }

        self.writeTabLine("\(FileWriter.TAB)}\n\n")
    }

    //
    // File IO utility funcs:
    //

    // Converts a string to data and writes to file.
    private func write(s : String)
    {
        if let writeString = s.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
        {
            self.outfile.writeData(writeString)
        }
        else
        {
            print("Error: Failed to write \(s) to file.\n")
        }
    }

    private func writeTabLine(s : String)
    {
        self.write("\(FileWriter.TAB)\(s)")
    }

    // Writes a string as a single line comment.
    private func writeCommentLine(s : String)
    {
        self.write("//\(FileWriter.TAB)\(s)\n")
    }
}